# Pandas Series Oluşturma

In [1]:
# pandas importing
import pandas as pd

In [3]:
my_data = pd.Series([1,2,3,4,5,15])
my_data
# pandas serisi index ve veri içinde değer döndürür.

0     1
1     2
2     3
3     4
4     5
5    15
dtype: int64

In [4]:
type(my_data)
# pandas seri tipi

pandas.core.series.Series

In [5]:
my_data.axes

[RangeIndex(start=0, stop=6, step=1)]

In [7]:
my_data.head(3)
# ilk n değer döndürme

0    1
1    2
2    3
dtype: int64

In [9]:
my_data.tail(3)
# son 3 değer

3     4
4     5
5    15
dtype: int64

In [8]:
my_data.values
# veri seti içindeki değerler nedir?

array([ 1,  2,  3,  4,  5, 15], dtype=int64)

# Index ismi belirleme

In [10]:
notes = pd.Series([65,47,56,89,100,92,36])
notes

0     65
1     47
2     56
3     89
4    100
5     92
6     36
dtype: int64

In [11]:
notes = pd.Series([65,47,56,89,100,92,36], index = ["note1","note2","note3","note4","note5","note6","note7"])

In [12]:
notes

note1     65
note2     47
note3     56
note4     89
note5    100
note6     92
note7     36
dtype: int64

In [15]:
notes["note1":"note4"]

note1    65
note2    47
note3    56
note4    89
dtype: int64

# Eleman işlemleri

In [20]:
import numpy as np

In [18]:
num = np.array([10,20,30,40])
pand = pd.Series(num)

In [19]:
pand

0    10
1    20
2    30
3    40
dtype: int32

In [21]:
pand[0:2]

0    10
1    20
dtype: int32

In [23]:
list(pand.items())

[(0, 10), (1, 20), (2, 30), (3, 40)]

In [24]:
pand.values

array([10, 20, 30, 40])

In [28]:
1 in pand
# 1 pand serisinin içinde mi ?

True

In [31]:
pand[[1,2]]

1    20
2    30
dtype: int32

# Pandas DataFrame

In [38]:
import numpy as np
m = np.array([55,45,35,25]).reshape(2,2)
m

array([[55, 45],
       [35, 25]])

In [42]:
df = pd.DataFrame(m,columns = ['deg1','deg2'])

In [43]:
df.size

4

In [44]:
df.values

array([[55, 45],
       [35, 25]])

In [45]:
df.axes

[RangeIndex(start=0, stop=2, step=1), Index(['deg1', 'deg2'], dtype='object')]

In [47]:
df.columns = ['degis1', 'degis2']

In [48]:
df.columns

Index(['degis1', 'degis2'], dtype='object')

# LOC & ILOC

In [52]:
import numpy as np
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ['var1','var2', 'var3'])
df

var1  var2  var3
0     1    11    24
1     9    13    21
2    18    25    28
3    15    26    14
4    17    29    14
5     9     9    27
6    11     5    22
7    27     9     1
8     6     5     7
9    15     2    20

In [54]:
df.loc[0:3]

var1  var2  var3
0     1    11    24
1     9    13    21
2    18    25    28
3    15    26    14

In [55]:
df.iloc[0:3]

var1  var2  var3
0     1    11    24
1     9    13    21
2    18    25    28

In [56]:
df.loc[0:3,"var3"]

0    24
1    21
2    28
3    14
Name: var3, dtype: int32

In [57]:
# degisken ismi gözlemi yapılmak isteniyorsa loc(location) kullanılır.
# index işlemleri için ise iloc(index location) kullanılır
df.iloc[0:5, "var1"]
# hata alırız...

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [60]:
df.iloc[0:5]["var1"]
# hata düzeltilmiş hali

0     1
1     9
2    18
3    15
4    17
Name: var1, dtype: int32

In [63]:
df[0:2][["var1","var2"]]

var1  var2
0     1    11
1     9    13

In [67]:
# Değişken filtreleme
# belirli verileri listeleyen kod.
df[df["var1"] > 15]
# var1 içerisinde 15'den büyük olan sayıları getiren kod

var1  var2  var3
2    18    25    28
4    17    29    14
7    27     9     1

In [72]:
df[(df.var1 > 5) & (df.var2 > 7)][["var1","var2"]]

var1  var2
1     9    13
2    18    25
3    15    26
4    17    29
5     9     9
7    27     9

In [75]:
df.loc[(df["var1"] > 10) & (df["var3"] > 5)][["var1","var2"]]

var1  var2
2    18    25
3    15    26
4    17    29
6    11     5
9    15     2

# Join işlemleri

In [1]:
import numpy as np
import pandas as pd

In [16]:
m = np.random.randint(1,30,size = (5,3))
df = pd.DataFrame(m, columns = ['col1','col2','col3'])
df

col1  col2  col3
0    23     4     1
1    23    26     4
2    27    19    21
3    18     3     5
4    11     9    24

In [17]:
df2 = df + 10
df2

col1  col2  col3
0    33    14    11
1    33    36    14
2    37    29    31
3    28    13    15
4    21    19    34

In [18]:
pd.concat([df,df2])

col1  col2  col3
0    23     4     1
1    23    26     4
2    27    19    21
3    18     3     5
4    11     9    24
0    33    14    11
1    33    36    14
2    37    29    31
3    28    13    15
4    21    19    34

In [20]:
?pd.concat

Signature:
pd.concat(
    objs: Union[Iterable[Union[ForwardRef('DataFrame'), ForwardRef('Series')]], Mapping[Union[Hashable, NoneType], Union[ForwardRef('DataFrame'), ForwardRef('Series')]]],
    axis=0,
    join='outer',
    ignore_index: bool = False,
    keys=None,
    levels=None,
    names=None,
    verify_integrity: bool = False,
    sort: bool = False,
    copy: bool = True,
) -> Union[ForwardRef('DataFrame'), ForwardRef('Series')]
Docstring:
Concatenate pandas objects along a particular axis with optional set logic
along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a dict is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silen

In [23]:
pd.concat([df,df2], ignore_index = True)

col1  col2  col3
0    23     4     1
1    23    26     4
2    27    19    21
3    18     3     5
4    11     9    24
5    33    14    11
6    33    36    14
7    37    29    31
8    28    13    15
9    21    19    34

In [24]:
# Inner join ile birleştirme işlemi
pd.concat([df,df2], join = 'inner')

col1  col2  col3
0    23     4     1
1    23    26     4
2    27    19    21
3    18     3     5
4    11     9    24
0    33    14    11
1    33    36    14
2    37    29    31
3    28    13    15
4    21    19    34

In [26]:
df1 = pd.DataFrame({'calisanlar': ['Mehmet', 'Ali','Berkay','Didem'],
                    'departman' : ['Manager','Procurement', 'IT', 'IK']
                   })
df1

calisanlar    departman
0     Mehmet      Manager
1        Ali  Procurement
2     Berkay           IT
3      Didem           IK

In [28]:
df2 = pd.DataFrame({'calisanlar': ['Mehmet', 'Ali', 'Berkay', 'Didem'],
                    'baslangic_tarih': ['2020', '2018', '2019','2015'] 
                   })
df2

calisanlar baslangic_tarih
0     Mehmet            2020
1        Ali            2018
2     Berkay            2019
3      Didem            2015

In [29]:
pd.merge(df1,df2)

calisanlar    departman baslangic_tarih
0     Mehmet      Manager            2020
1        Ali  Procurement            2018
2     Berkay           IT            2019
3      Didem           IK            2015

In [30]:
pd.merge(df1,df2, on = 'calisanlar')
# calisanlar ortak kolonunda birleştirme işlemi 

calisanlar    departman baslangic_tarih
0     Mehmet      Manager            2020
1        Ali  Procurement            2018
2     Berkay           IT            2019
3      Didem           IK            2015

# Aggregating

* count()
* sum()
* mean()
* min()
* max()
* std()
*var()

In [32]:
# örnek dataset yükleme
import seaborn as sns
df = sns.load_dataset('planets')
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [41]:
df.shape
# 1035 gözlem ve 6 değişken var...

(1035, 6)

In [42]:
print("Gezegenlerin ortalama kütlesi:" + str(df['mass'].mean()))
print("Maksimum gezegen kütlesi:" + str(df['mass'].max()))
print("Minimum gezegen kütlesi:" + str(df['mass'].min()))
print("Gezegen kütles standart sapması:" + str(df['mass'].std()))

Gezegenlerin ortalama kütlesi:2.6381605847953233
Maksimum gezegen kütlesi:25.0
Minimum gezegen kütlesi:0.0036
Gezegen kütles standart sapması:3.8186166509616046


# Betimsel istatistik çıkarma

In [44]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [45]:
# veri seti içinde eksik gözlemlerin silinmesi ile betimsel istatistik çıkarma...
df.dropna().describe().T

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

In [ ]:
# Veri setinde betimsel istatistiklerde ufak değişiklikler olduğu görülür.

In [48]:
dt = pd.DataFrame({'Grup': ['A', 'B', 'C', 'D', 'E','A','B','C','D'],
                  'Deger': [36,45,68,58,96,45,68,87,46]})
dt

Grup  Deger
0    A     36
1    B     45
2    C     68
3    D     58
4    E     96
5    A     45
6    B     68
7    C     87
8    D     46

In [58]:
dt.groupby("Grup").sum()

Deger
Grup       
A        81
B       113
C       155
D       104
E        96

In [59]:
df = sns.load_dataset('planets')
df.head()


method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [61]:
df.groupby("method")['distance'].mean()

method
Astrometry                         17.875000
Eclipse Timing Variations         315.360000
Imaging                            67.715937
Microlensing                     4144.000000
Orbital Brightness Modulation    1180.000000
Pulsar Timing                    1200.000000
Pulsation Timing Variations              NaN
Radial Velocity                    51.600208
Transit                           599.298080
Transit Timing Variations        1104.333333
Name: distance, dtype: float64

In [64]:
print("Kütleye göre betimsel istatistik:...")
df.groupby("method")['mass'].describe().T

Kütleye göre betimsel istatistik:...


method  Astrometry  Eclipse Timing Variations  Imaging  Microlensing  \
count          0.0                   2.000000      0.0           0.0   
mean           NaN                   5.125000      NaN           NaN   
std            NaN                   1.308148      NaN           NaN   
min            NaN                   4.200000      NaN           NaN   
25%            NaN                   4.662500      NaN           NaN   
50%            NaN                   5.125000      NaN           NaN   
75%            NaN                   5.587500      NaN           NaN   
max            NaN                   6.050000      NaN           NaN   

method  Orbital Brightness Modulation  Pulsar Timing  \
count                             0.0            0.0   
mean                              NaN            NaN   
std                               NaN            NaN   
min                               NaN            NaN   
25%                               NaN            NaN   
50%                               NaN            NaN   
75%                               NaN            NaN   
max                               NaN            NaN   

method  Pulsation Timing Variations  Radial Velocity  Transit  \
count                           0.0       510.000000     1.00   
mean                            NaN         2.630699     1.47   
std                             NaN         3.825883      NaN   
min                             NaN         0.003600     1.47   
25%                             NaN         0.225250     1.47   
50%                             NaN         1.260000     1.47   
75%                             NaN         3.000000     1.47   
max                             NaN        25.000000     1.47   

method  Transit Timing Variations  
count                         0.0  
mean                          NaN  
std                           NaN  
min                           NaN  
25%                           NaN  
50%                           NaN  
75%                           NaN  
max                           NaN

In [65]:
dt = pd.DataFrame({'Grup': ['A', 'B', 'C', 'D', 'E','A','B','C','D'],
                  'Deger': [36,45,68,58,96,45,68,87,46]})
dt

Grup  Deger
0    A     36
1    B     45
2    C     68
3    D     58
4    E     96
5    A     45
6    B     68
7    C     87
8    D     46

In [69]:
dt.groupby("Grup").aggregate([max, min, np.median])

Deger           
       max min median
Grup                 
A       45  36   40.5
B       68  45   56.5
C       87  68   77.5
D       58  46   52.0
E       96  96   96.0

In [71]:
df = pd.DataFrame({'Grup': ['A', 'B', 'C', 'D', 'E','A','B','C','D'],
                  'Deger': [36,45,68,58,96,45,68,87,46]})
df

Grup  Deger
0    A     36
1    B     45
2    C     68
3    D     58
4    E     96
5    A     45
6    B     68
7    C     87
8    D     46

In [77]:
# İleri teknik filtreleme için fonksiyon kullanma...
def calc_std(x):
    return x['Deger'].std() > 9

In [78]:
df.groupby("Grup").filter(calc_std)

Grup  Deger
1    B     45
2    C     68
6    B     68
7    C     87

# Apply

In [83]:
dff = df.iloc[:,1:2]

In [84]:
dff.apply(np.sum)

Deger    549
dtype: int64

In [88]:
dff.apply(np.mean)

Deger    61.0
dtype: float64

# Pivot Tables

In [89]:
import pandas as pd
import seaborn as sns
df = sns.load_dataset("titanic")
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [96]:
# ilkel yoldan pivot table oluşumu
df.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()

survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [98]:
df.pivot_table("survived", index = "sex", columns = "class")

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447