# NumPy Özellikleri

In [2]:
# Hızlı matematiksel ve boyutsal işlemler yapmaya yardımcı olur.
# optimizasyon ve iyileştirme anlamında da yardımcı olur.
# yüksek seviye matematiksel işlemler için daha az ve karmaşık olmayan kodlarla işlem yapma imkanı.
a = [1,2,3,4,5]
b = [2,3,4,5,6]


In [3]:
ab = []
for i in range(0,len(a)):
    ab.append(a[i]* b[i])
ab    

[2, 6, 12, 20, 30]

In [4]:
# aynı işlemi numPy kütüphanesi ile yapalım.
# numPy kütüphanesini import etme işlemi
import numpy as np

In [5]:
# numPy array oluşturma işlemi
a = np.array([1,2,3,4,5])
b = np.array([2,3,4,5,6])
a*b 

array([ 2,  6, 12, 20, 30])

# NumPy array oluşturma

In [6]:
# NumPy tek tipte(fixed type) veri tutar
a = np.array([3.14,2.45,3,8])
a

array([3.14, 2.45, 3.  , 8.  ])

In [7]:
# numPy tüm sayıları float veri tipine dönüştürdü...
type(a)
#numPy veri tipleri ndarray bicimindedir.

numpy.ndarray

In [8]:
# numPy ile sıfır arrayı oluşturma
np.zeros(10,dtype = int)
# 10 haneli 0 numPy arrayı

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
np.ones(10,dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
# 2 boyutlu 1li matris oluşturma
np.ones((4,4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [11]:
np.arange(0,20,5)
# tek boyutlu 0 ile 20 arasında 5er 5 er artan işlem için

array([ 0,  5, 10, 15])

In [15]:
# normal dağılımlı rasgele vektör oluşturma.
np.random.normal(10,4,(4,4))
# 10 ortalamalı 4 standart sapmalı 4'E 4'lük bir matris

array([[ 7.6797606 ,  7.11053523, 13.55090808,  8.50641849],
       [13.35048992, 18.35066034,  7.51798578,  8.74410488],
       [ 8.68876688,  9.62633722, 11.49314995, 10.68979882],
       [ 9.82103835,  5.73913026,  7.91630406,  6.93706547]])

In [17]:
#integer değerler ile rastgele değer oluşturma.
np.random.randint(0,10,(4,4))

array([[1, 1, 1, 6],
       [1, 2, 1, 4],
       [5, 9, 9, 4],
       [3, 8, 9, 6]])

# NumPy Özellikleri

* **ndim** : Boyut sayısını verir
* **shape** : Boyut bilgisini verir   
* **size**: Toplam eleman bilgisini verir
* **dtype**: Array veri tipini verir.    

In [30]:
a = np.random.randint(10,size = 10)

In [31]:
a.ndim
# tek boyutlu array

1

In [32]:
a.shape

(10,)

In [33]:
a.size

10

In [34]:
a.dtype

dtype('int32')

In [35]:
b = np.random.randint(20,size = (3,5))

In [36]:
b.ndim
#2 Boyutlu

2

In [37]:
b.shape

(3, 5)

In [38]:
b.size

15

In [39]:
b.dtype

dtype('int32')

# Reshape

In [40]:
a = np.arange(1,10)

In [41]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a.ndim

1

In [46]:
b = a.reshape((3,3))
# Tek boyuttan iki boyuta çevirme işlemi

In [47]:
b.ndim

2

# Birleştirme(concatenate) işlemi

In [49]:
a1 = np.array([0,2,4,6])
a2 = np.array([1,3,5,7])


In [52]:
cc = np.concatenate([a1,a2])
cc

array([0, 2, 4, 6, 1, 3, 5, 7])

In [53]:
a3 = np.array([9,11,13,15])

In [55]:
cc = np.concatenate([a1,a2,a3])
cc

array([ 0,  2,  4,  6,  1,  3,  5,  7,  9, 11, 13, 15])

In [61]:
# 2 boyutlu matrisleri birleştirme
td = np.array([[0,2,4,6],
              [1,3,5,7]])
               
td

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [64]:
con = np.concatenate([td,td], axis = 0)
con
# default olarak axis = 0 yani satır bazlı birleştirme işlemi yapıldı.

array([[0, 2, 4, 6],
       [1, 3, 5, 7],
       [0, 2, 4, 6],
       [1, 3, 5, 7]])

In [66]:
conn = np.concatenate([td,td], axis = 1)
conn
# axis = 1 sütun bazlı birleştirme yapıldı...

array([[0, 2, 4, 6, 0, 2, 4, 6],
       [1, 3, 5, 7, 1, 3, 5, 7]])

# Array Ayırma(split) işlemi

In [72]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
np.split(a,[2])
# satır bazında 2 farklı array ayırma işlemi

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [75]:
a1, a2 = np.hsplit(a,[2])
#sütun bazında 2'ye ayırma işlemi...

In [76]:
a1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [77]:
a2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [78]:
v1,v2 = np.vsplit(a,[2])

In [79]:
v1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [80]:
v2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# Sıralama(sort işlemleri)

In [83]:
a = np.array([48,16,22,1,25,68,45,99,97])

In [84]:
np.sort(a)

array([ 1, 16, 22, 25, 45, 48, 68, 97, 99])

In [85]:
type(a)

numpy.ndarray

In [87]:
a.sort()
a

array([ 1, 16, 22, 25, 45, 48, 68, 97, 99])

In [88]:
type(a)

numpy.ndarray

In [89]:
a = np.random.normal(20,5,(3,3))

In [90]:
a

array([[16.06242898, 20.96822098, 14.48604611],
       [22.41137966, 25.87272934, 21.0134793 ],
       [21.6493586 , 10.21301511, 28.84830828]])

In [92]:
np.sort(a, axis = 0)
#sutün bazlı sıralama

array([[16.06242898, 10.21301511, 14.48604611],
       [21.6493586 , 20.96822098, 21.0134793 ],
       [22.41137966, 25.87272934, 28.84830828]])

In [93]:
np.sort(a, axis = 1)
#satır bazlı sıralama

array([[14.48604611, 16.06242898, 20.96822098],
       [21.0134793 , 22.41137966, 25.87272934],
       [10.21301511, 21.6493586 , 28.84830828]])

# NumPy ile İndex işlemleri

In [95]:
import numpy as np

In [98]:
a = np.random.normal(10, size = 10)

In [99]:
a

array([10.87340384,  9.66894698,  8.96457175,  8.64966854, 10.35935186,
       12.91415823,  7.8004135 ,  8.99624236, 12.96690091,  9.84864346])

In [100]:
a[0]
#ilk indexe erişmek

10.873403836602906

In [101]:
a[-1]
# son indexe erişmek

9.848643459187695

In [102]:
# son indexin sonucunu değiştirmek
a[-1] = 10.02

In [103]:
a

array([10.87340384,  9.66894698,  8.96457175,  8.64966854, 10.35935186,
       12.91415823,  7.8004135 ,  8.99624236, 12.96690091, 10.02      ])

In [104]:
b = np.random.randint(20,size = (4,4))

In [106]:
b

array([[ 3,  4,  3, 12],
       [12,  9, 18, 19],
       [17,  7, 16, 12],
       [ 0, 10,  9, 15]])

In [107]:
b[1,1]
# matris içindeki veriye erişmek...

9

In [108]:
b[0,0]

3

# Slice işlemleri

In [109]:
a = np.arange(20,30)

In [110]:
a[::]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [111]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [112]:
a[1::2]

array([21, 23, 25, 27, 29])

In [113]:
a[0::5]

array([20, 25])

# iki boyutlu slice işlemleri

In [114]:
m = np.random.randint(10, size = (5,5))

In [115]:
m

array([[9, 1, 3, 0, 9],
       [0, 1, 6, 6, 3],
       [4, 9, 8, 2, 6],
       [6, 3, 6, 8, 3],
       [1, 5, 9, 0, 2]])

In [116]:
m[:,0]
# tüm satırları al ve ilk sütunu al...

array([9, 0, 4, 6, 1])

In [117]:
m[0:3,:]
# ilk 3 satırı al ve tüm sutunları dahil et...

array([[9, 1, 3, 0, 9],
       [0, 1, 6, 6, 3],
       [4, 9, 8, 2, 6]])

In [118]:
m[0:2,2:4]

array([[3, 0],
       [6, 6]])

# Alt kümelere erişmek

In [119]:
m

array([[9, 1, 3, 0, 9],
       [0, 1, 6, 6, 3],
       [4, 9, 8, 2, 6],
       [6, 3, 6, 8, 3],
       [1, 5, 9, 0, 2]])

In [121]:
alt_m = m[0:3,0:3]
alt_m

array([[9, 1, 3],
       [0, 1, 6],
       [4, 9, 8]])

In [124]:
alt_m[0,0] = 99
alt_m[1,1] =45
alt_m

array([[99,  1,  3],
       [ 0, 45,  6],
       [ 4,  9,  8]])

In [125]:
m

array([[99,  1,  3,  0,  9],
       [ 0, 45,  6,  6,  3],
       [ 4,  9,  8,  2,  6],
       [ 6,  3,  6,  8,  3],
       [ 1,  5,  9,  0,  2]])

In [ ]:
# m matrisinde yaptığımız değişiklik.
# m matrisinde yaptığımız değişiklerin matrisimizi etkilemesini istemiyorsak copy() methodu kullanılır..

In [128]:
alt_b = m[0:2,0:2].copy()
alt_b

array([[99,  1],
       [ 0, 45]])

In [130]:
alt_b[0,0] = 3
alt_b[1,1] = 3

In [131]:
alt_b

array([[3, 1],
       [0, 3]])

In [132]:
m
# m matrisinden aldığımız alt kümede değişiklik olurken, 
# matrisimizde bir değişiklik olmadı...

array([[99,  1,  3,  0,  9],
       [ 0, 45,  6,  6,  3],
       [ 4,  9,  8,  2,  6],
       [ 6,  3,  6,  8,  3],
       [ 1,  5,  9,  0,  2]])

# Fancy Index ile erişim

In [135]:
data = np.arange(0,30,3)
data

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [140]:
fancy = [1,3,5]

In [141]:
fancy

[1, 3, 5]

In [142]:
data[fancy]

array([ 3,  9, 15])

In [143]:
a =np.arange(9).reshape(3,3)

In [144]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [145]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [146]:
a[satir,sutun]

array([1, 5])

# Koşullu işlemler

In [147]:
a = np.array([1,2,3,4,5])

In [148]:
a > 5

array([False, False, False, False, False])

In [149]:
a > 3

array([False, False, False,  True,  True])

In [150]:
a[a > 2]

array([3, 4, 5])

In [151]:
a [a ==3]

array([3])

In [152]:
a [a != 5 ]

array([1, 2, 3, 4])

In [158]:
# diziden çıkarma işlemi yapmak
a - 5

array([-4, -3, -2, -1,  0])

In [160]:
np.subtract(a,1)
# diziden ufunc ile çıkarma yapma

array([0, 1, 2, 3, 4])

In [161]:
np.divide(a,5)
# 5 ile bölünme işlemi

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [153]:
a * 2

array([ 2,  4,  6,  8, 10])

In [154]:
a % 2 == 0

array([False,  True, False,  True, False])

In [155]:
a [ a % 2 == 0]
 # array içinde 2 ile tam bölünebilen sayılar(çift sayılar)

array([2, 4])

In [162]:
np.mod(a,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [156]:
a * 5 / 2

array([ 2.5,  5. ,  7.5, 10. , 12.5])

In [157]:
a ** 3
# kübünü alma işlemi

array([  1,   8,  27,  64, 125], dtype=int32)

In [163]:
np.cos(180)
#cos180 değeri(trigonometrik işlemler)

-0.5984600690578581

In [164]:
np.sin(360)

0.9589157234143065

In [167]:
?np.sin
# numPy içinde sinüs işlemi ile ilgili nasıl bilgiler var?

Call signature:  np.sin(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'sin'>
File:            c:\users\mak\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:      
sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Trigonometric sine, element-wise.

Parameters
----------
x : array_like
    Angle, in radians (:math:`2 \pi` rad equals 360 degrees).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its ori

In [168]:
np.sin(np.pi/2.)

1.0

# NumPy ile temel istatistik hesaplamaları

In [175]:
grades1 =np.array([80,60,40,50,30,95,98,76])
grades2 = np.array([65,45,85,70,90,60,56,45])

In [178]:
grades1.min()
# en az not hangisinde?

30

In [180]:
grades2.min()

45

In [184]:
grades1.max()


98

In [183]:
grades2.max()

90

In [185]:
grades1.mean()

66.125

In [190]:
grades2.mean()

64.5

In [187]:
grades1.std()

23.51827746668535

In [188]:
grades2.std()

15.628499608087784

In [ ]:
# 1.notlarda ortalamadan sapma daha fazla, notlar düzgün dağılmamış(2.ye kıyasla)